name: 'Bangumi.TV Collection Action'
description: 'Bangumi.TV 每日同步生成个人收藏卡片，自动上传仓库的 Github Action 服务'
inputs:
  github-token:
    description: "Github Token"
    required: true
  bgm-user-id:
    description: '班固米的用户ID，设置过用户名请使用用户名'
    required: true
    default: 'xiaoyvyv'
  bgm-img-path:
    description: '图片卡片上传保存路径'
    required: true
    default: 'bgm/left.svg'
  show-animes:
    description: '是否显示动画'
    required: false
    default: true
  show-mangas:
    description: '是否显示漫画'
    required: false
    default: true
  show-games:
    description: '是否显示游戏'
    required: false
    default: true
  show-characters:
    description: '是否显示角色'
    required: false
    default: true
  favorite-animes:
    description: '展示的动画id(用逗号分隔, 不填则自动生成)'
    required: false
    default: ''        
outputs:
  message:
    description: '信息'
runs:
  using: 'node18'
  steps:
    - run: |
      npm install
      node index.js
    shell: bash  
