name: Build-Latest

on:
    push:
        branches:
          - main

jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
  
      - name: Install dependencies
        run: npm ci
  
      - name: Build with ncc
        run: npx @vercel/ncc build index.js -o dist
  
      - name: Push to release branch
        run: |
          git config --local user.email "3262392248@qq.com"
          git config --local user.name "Kom3ng"
          git checkout -b latest
          git add dist/*
          git add action.yml
          git commit -m "release"
          git push origin latest