name: Build-V

on:
    push:
        tags:
            - 'v*'


jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
  
      - name: Install dependencies
        run: npm install

      - name: Build with ncc
        run: npx @vercel/ncc build index.js -o dist

      - run: cp -R tmpl dist/
  
      - name: Push to version branch
        run: |
          git config --local user.email "3262392248@qq.com"
          git config --local user.name "Kom3ng"
          git checkout -b ${GITHUB_REF#refs/tags/}
          git add -f dist/*
          git add action.yml
          git commit -m "${GITHUB_REF#refs/tags/}"
          git push -f origin ${GITHUB_REF#refs/tags/}