name: Bgm-Data-Sync
on:
  # 每日零点执行（这个配置最小间隔5分钟）
  schedule: [{ cron: '0 0 * * *' }]
  push:
    branches:
      - main

jobs:
  bgm-sync:
    runs-on: ubuntu-latest
    name: 每日同步BGM收藏卡片
    permissions:
      contents: write
    steps:
      - name: Bgm Collection Card
        id: bgm
        uses: Kom3ng/bangumi-action@main
        with:
          github-token: '${{secrets.GITHUB_TOKEN}}'
          bgm-user-id: 'astrack'
          bgm-img-path: 'bgm/card.svg'
          show-characters: false

      - name: Get the output image url
        run: echo "图片生成的链接地址 ${{ steps.bgm.outputs.message }}"